openapi: 3.0.1
info:
  title: Task Tracker API
  description: API for creating, updating, starting and ending tasks
  version: 1.0.0
servers:
  - url: /tasks
    description: Main Tasks API point

paths:
  /:
    get:
      summary: Get all tasks
      description: Returns a list of all tasks
      responses:
        '200':
          description: A JSON array of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  /createTask:
    post:
      summary: Create a new task
      description: Adds a new task and saves it in Database
      requestBody:
        description: Task object to be created and saved
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task successfully created
  /updateTask:
    post:
      summary: Update an existing task
      description: Updates the name and description of a task
      requestBody:
        description: Task to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task successfully updated
  /startTask:
    post:
      summary: Start a task
      description: Sets task's start time
      parameters:
        - name: id
          in: query
          required: true
          description: ID of the task to update start time
          schema:
            type: integer
      responses:
        '200':
          description: Task successfully started
  /endTask:
    post:
      summary: End a task
      description: Sets task's end time
      parameters:
        - name: id
          in: query
          required: true
          description: ID of the task to end
          schema:
            type: integer
      responses:
        '200':
          description: Task successfully ended

components:
  schemas:
    Task:
      type: object
      properties:
        name:
          type: string
          description: Name of the task
        description:
          type: string
          description: Description of the task
